server:
  port: 8087

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
            
        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/videos/**
          filters:
            - AuthenticationFilter
            
        - id: SECURITY-SERVICE
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
          
        - id: COMMENT-SERVICE
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comment/**
          filters:
            - AuthenticationFilter
            
        - id: DESC-SERVICE
          uri: lb://DESC-SERVICE
          predicates:
            - Path=/description/**
          filters:
            - AuthenticationFilter
          
        - id: MEDIA-SERVICE
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/media/**
          filters:
            - AuthenticationFilter
            
        - id: TAG-SERVICE
          uri: lb://TAG-SERVICE
          predicates:
            - Path=/tags/**
          filters:
            - AuthenticationFilter 

eureka:
  instance:
    client:
      fetch-registry: true
      prefer-ip-address: true
      register-with-eureka: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      spring:
  main:
    web-application-type: servlet
   
    allow-bean-definition-overriding: true
      


